export const pathDefault = {
  homePage: "/",
  searchPage: "/search",
  signInAdmin: "/signin-admin",
  admin: "/admin",
  dashBoard: "/admin/dashboard",
  managerUser: "/admin/manager-user",
  managerRoom: "/admin/manager-room",
  managerReservation: "/admin/manager-reservation",
  managerLocation: "/admin/manager-location",
  signIn: "/sign-in",
  signUp: "/sign-up",
  AuthPage: "/Auth",
  Profile: "/profile",
  roomDetailPage: "/rooms/:id",
  payment: "/payment",
  favorite: "/favorite",
};
